### PR TITLE
fixes. additional options

### PR DESCRIPTION
**Pull request by thecodeassassin**
* Added isDoubleElimination, disableTeamEdit and disableEditButtons options
* fixed proper line endings in source file

### CODE REVIEW

**Comment by thecodeassassin** [comment]
@teijo would it be possible to merge this PR?

**Comment by teijo** [comment]
Thanks for making a PR, I'll try to go through it this weekend.

If the new functionality is something that would be merged, then you should trim the PR a bit to keep the history of changes clear.

I recommend discarding the style changes and squashing the commits so that e.g. the compilation results accidentally included in 7bf178e don't need to be removed right in the next commit ff4022e. The PR should include only the changes required for the new functionality. You should have multiple commits of course if they contain changes not related to each other.

**Comment by thecodeassassin** [comment]
No problem can do.only why do you want to the style changes to be discarded? My editor goes beserk because of all the missing semicolons.

**Comment by teijo** [comment]
`disableEditButtons` already exists by not providing `save` callback in init. From https://github.com/teijo/jquery-bracket/blob/master/src/jquery.bracket.ts#L1114

```javascript
    if (opts.save)
      embedEditButtons(topCon, data, opts)
```

Addressed  `isDoubleElimination` in #36. Use `[[[[]]], [], []]` as result to init as double elimination instead.

Regarding style changes, I don't see it as a priority as it'll touch nearly every line. If it's done, it has to be enforced by a linting tool as it's impossible to manually adhere to a style perfectly.

What was the functionality of `disableTeamNameEdit`? To me, it relates to editing to the bracket, but that can be disabled by not defining `save` in init.

**Comment by thecodeassassin** [comment]
The reasons are:

- wanting the save option but not the buttons
- wanting the save option but team names need to be static

It makes the library more flexible

**Comment by teijo** [comment]
I can see how that could make for a better workflow - to prevent user from changing tournament size or participants (from UI) while the tournament is ongoing. I think it should be an OK feature. Just thinking about the API.

Instead of creating a lot of top level booleans that start to conflict with each other, like `onMatchClick`and `onMatchHover` that cannot be used while `save` is defined, howabout a extending `save`? The options could be configured under `save` as object as they are both related to the save functionality.

Keep the old API which is:

```javascript
$('div#selector').bracket({
  save: function() {}
})
```

But allow extending `save` by:

```javascript
$('div#selector').bracket({
  save: {
    callback: function() {},
    disableNameEdit: true,
    disableFormatEdit: true // idk if "format" is descriptive enough...
  }
})
```

I'd prefer not referring to the buttons as `disableEditButtons` as it doesn't reflect what functionality the setting changes.

We could close this pull request and make a new one for just enhancing the save functionality. What do you think?

**Comment by teijo** [comment]
Master branch includes now the support for disabling name editing and resizing (`disableTeamEdit` and `disableResize`). Will get included into the next release. Now at top level but as I see my old suggestion here again, might update it for the release :)

**Pull request closed without merging**
