### PR TITLE
Rolling wolf patch 2

### PR DESCRIPTION
**Pull request by rollingWolf**
Path-1-1 didnt support double elimination properly. This one does.

### CODE REVIEW

**Comment by rollingWolf** [comment]
Sorry I closed it because I thought I had found a bug but that proved not to be the case.

**Comment by brgaulin** [comment]
@rollingWolf were you able to get this working with teams in the range of 9-14 ?
Seems when I input [9,14] teams the script can't render. But this patch does do 15 and 31 teams well.

I have made some other tweaks on my local copy, so not sure if those affect it, but I would love to get BYE support in this library =)

**Comment by brgaulin** [comment]
ignore my previous comment, feeding the data with byes in round 1 seems to render fine. This looks great!

**Comment by teijo** [comment]
Sorry for leaving this hanging, the project was on a hiatus for a long time. Quote from #8 

>Seems I've unfortunately failed to follow-up with #33 even though I've read and referenced it.

> I feel the approach is a bit too inflexible as such as it reserves 'BYE' as a special team name and forces results to 1-0. I feel something more flexible would work better in the long run as you wouldn't have to break backwards compatibility after rolling back some earlier decision.

It's still a valid approach in a sense so I'll keep it open for now if someone wants to use it.

**Comment by teijo** [comment]
Bye support included into 0.8.0, closing.

**Pull request closed without merging**
